django/장고 정리/09_ORM_with view_0330/0330_장고실습/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
]

django/장고 정리/09_ORM_with view_0330/0330_장고실습/todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/complete/', views.complete, name='complete'),


]

django/장고 정리/09_ORM_with view_0330/0330_장고실습/todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField(null=True)
    completed = models.BooleanField(default=False)
    priority = models.IntegerField(default=3)
    created_at = models.DateField(auto_now_add=True)
    deadline = models.DateField(null=True)

django/장고 정리/09_ORM_with view_0330/0330_장고실습/todos/views.py
from django.shortcuts import render, redirect
from .models import Todo

# Create your views here.
def index(request):
    todos = Todo.objects.all()
    context = {
        'todos' : todos,
    }
    return render (request, 'todos/index.html', context)

def detail(request, pk):
    todo = Todo.objects.get(pk=pk)
    context = {
        'todo' : todo,
    }

    return render(request, 'todos/detail.html', context)

def new(request):
    return render(request, 'todos/new.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    completed = request.POST.get('completed')
    priority = request.POST.get('priority')
    deadline = request.POST.get('deadline')
    print(request.POST)
   

    todo = Todo(title=title, content=content, priority=priority, deadline=deadline, completed=completed)
    todo.save()
    
    return redirect('todos:detail', todo.pk)

def delete(request, pk):
    todo = Todo.objects.get(pk=pk)

    todo.delete()
    return redirect('todos:index')

def edit(request, pk):
    todo = Todo.objects.get(pk=pk)

    context = {
        'todo' : todo,
    }
    return render(request, 'todos/edit.html', context)

def update(request, pk):
    todo = Todo.objects.get(pk=pk)

    todo.title = request.POST.get('title')
    todo.content = request.POST.get('content')
    todo.priority = request.POST.get('priority')
    todo.deadline = request.POST.get('deadline')

    todo.save()
    return redirect('todos:detail', todo.pk)

def complete(request, pk):
    todo = Todo.objects.get(pk=pk)
    print(type(request.POST.get('completed')))
    if request.POST.get('completed') == 'True':
        print(1)
        todo.completed = False
        todo.save()
    elif request.POST.get('completed') == 'False':
        print(2)
        todo.completed = True
        todo.save()

    return redirect('todos:index')

django/장고 정리/09_ORM_with view_0330/0330_장고실습/todos/templates/todos/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  {% block style %}
  {% endblock style %}
</head>
<body>
  {% comment %} 자식 템플릿 공간 {% endcomment %}
  {% block content %}
  {% endblock content %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

django/장고 정리/09_ORM_with view_0330/0330_장고실습/todos/templates/todos/detail.html
{% extends 'todos/base.html' %}

{% block content %}
  <ul class="list-group list-group-horizontal">
    <li class="list-group-item list-group-item-dark" style="width: 100px">제목</li>
    <li class="list-group-item list-group-item-dark" style="width: 300px">{{ todo.title }}</li>
  </ul>
  <ul class="list-group list-group-horizontal">
    <li class="list-group-item list-group-item-dark" style="width: 100px">내용</li>
    <li class="list-group-item list-group-item-dark" style="width: 300px">{{ todo.content }}</li>
  </ul>
  <ul class="list-group list-group-horizontal">
    <li class="list-group-item list-group-item-dark" style="width: 100px">완성</li>
    <li class="list-group-item list-group-item-dark" style="width: 300px">{{ todo.completed }}</li>
  </ul>
  <ul class="list-group list-group-horizontal">
    <li class="list-group-item list-group-item-dark" style="width: 100px">우선순위</li>
    <li class="list-group-item list-group-item-dark" style="width: 300px">{{ todo.priority }}</li>
  </ul>
  <ul class="list-group list-group-horizontal">
    <li class="list-group-item list-group-item-dark" style="width: 100px">마감기한</li>
    <li class="list-group-item list-group-item-dark" style="width: 300px">{{ todo.deadline }}</li>
  </ul>
  <form action="{% url 'todos:delete' todo.pk %}" method="POST">
    {% csrf_token %}
    <input class="btn btn-secondary mt-2" type="submit" value="삭제">
  </form>
  <a class="btn btn-secondary mt-2" href="{% url 'todos:edit' todo.pk %}">수정하기</a>
  <a class="btn btn-secondary mt-2" href="{% url 'todos:index' %}">뒤로가기</a>
{% endblock content %}

django/장고 정리/09_ORM_with view_0330/0330_장고실습/todos/templates/todos/edit.html
{% extends 'todos/base.html' %}

{% block content %}
  <form action={% url 'todos:update' todo.pk %} method="POST">
    {% csrf_token %}
    <div class="input-group mb-3" style="width: 500px">
      <label class="input-group-text" for="title">제목</label>
      <input class="form-control" type="text" name="title" id="title" value="{{ todo.title }}">
    </div>

    <div class="input-group mb-3" style="width: 500px">
      <label class="input-group-text" for="content">내용</label>
      <textarea class="form-control" name="content" id="content" cols="30" rows="10">{{ todo.content }}</textarea>
    </div>
    
    <div class="input-group mb-3" style="width: 500px">
      <label class="input-group-text" for="priority">우선순위</label>
      <input class="form-control" type="text" name="priority" id="priority" value="{{ todo.priority }}">
    </div>

    <div class="input-group mb-3" style="width: 500px">
      <label class="input-group-text" for="deadline">마감기한</label>
      <input class="form-control" type="date" name="deadline" id="deadline" value="{{ todo.deadline }}">
    </div>

    <div class="mb-3">
      <label for="completed">완료</label>
      <span>T</span>
      <input type="checkbox" name = "completed" id="completed" value="True">
      <span>F</span>
      <input type="checkbox" name= "completed" id="completed" value="False">
    </div>

    <div>
      <input class="btn btn-outline-primary" type="submit">
    </div>

    
  </form>
  <a class="btn btn-outline-light" href="{% url 'todos:index' %}">뒤로가기</a>
{% endblock content %}

django/장고 정리/09_ORM_with view_0330/0330_장고실습/todos/templates/todos/index.html
{% extends 'todos/base.html' %}

{% block content %}
  <div class="ms-2 mt-2">
    <a class="btn btn-success mb-3" href="{% url 'todos:new' %}">새로만들기</a>
    {% for todo in todos %}
      <p class= "mb-2">
        <form action={% url 'todos:complete' todo.pk %} method="POST">
          {% csrf_token %}
          <a class="btn btn-outline-success" style="width : 50px" href="{% url 'todos:detail' todo.pk %}">{{ todo.pk }}</a>
          <input class="btn btn-outline-success" style="width : 70px" type="text" name="completed" value={{ todo.completed }}>
          <input class="btn btn-outline-success" type="submit" value="완료">
        </form>
      </p>
    {% endfor %}
  </div>
{% endblock content %}

django/장고 정리/09_ORM_with view_0330/0330_장고실습/todos/templates/todos/new.html
{% extends 'todos/base.html' %}

{% block content %}
  <form action={% url 'todos:create' %} method="POST">
    {% csrf_token %}
    <div class="input-group mb-3" style="width: 500px">
      <label class="input-group-text" for="title">제목</label>
      <input class="form-control" type="text" name="title" id="title">
    </div>

    <div class="input-group mb-3" style="width: 500px">
      <label class="input-group-text" for="content">내용</label>
      <textarea class="form-control" name="content" id="content" cols="30" rows="10"></textarea>
    </div>
    
    <div class="input-group mb-3" style="width: 500px">
      <label class="input-group-text" for="priority">우선순위</label>
      <input class="form-control" type="text" name="priority" id="priority">
    </div>

    <div class="input-group mb-3" style="width: 500px">
      <label class="input-group-text" for="deadline">마감기한</label>
      <input class="form-control" type="date" name="deadline" id="deadline">
    </div>

    <div class="mb-3">
      <label for="completed">완료</label>
      <span>T</span>
      <input type="checkbox" name = "completed" id="completed" value="True">
      <span>F</span>
      <input type="checkbox" name= "completed" id="completed" value="False">
    </div>

    <div>
      <input class="btn btn-outline-primary" type="submit">
    </div>

    
  </form>
  <a class="btn btn-outline-light" href="{% url 'todos:index' %}">뒤로가기</a>
{% endblock content %}