django/장고 실습 파일/0412장고실습/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('profile/<user_pk>/', views.profile, name='profile'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

django/장고 실습 파일/0412장고실습/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reviews/', include('reviews.urls')),
    path('accounts/', include('accounts.urls')),
]

django/장고 실습 파일/0412장고실습/reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/comments/', views.comment_create, name='comment_create'),
    path(
        '<int:review_pk>/comments/<int:comment_pk>/delete/',
        views.comment_delete,
        name='comment_delete',
    ),
]

django/장고 실습 파일/0412장고실습/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

django/장고 실습 파일/0412장고실습/reviews/models.py
from django.db import models
from django.conf import settings

class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=80)
    content = models.TextField(null=False)
    movie = models.CharField(max_length=80)


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    content = models.TextField(null=False)

django/장고 실습 파일/0412장고실습/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        )

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = (
            'email',
            'first_name',
            'last_name',
        )

django/장고 실습 파일/0412장고실습/reviews/forms.py
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('title', 'content', 'movie')


class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.TextInput())

    class Meta:
        model = Comment
        fields = ('content',)

django/장고 실습 파일/0412장고실습/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from .forms import CustomUserCreationForm, CustomUserChangeForm


@login_required
def profile(request, user_pk):
    user = get_user_model().objects.get(pk=user_pk)

    context = {
        'user': user,
    }

    return render(request, 'accounts/profile.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('reviews:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('reviews:index')
    else:
        form = AuthenticationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('reviews:index')


def signup(request):
    if request.user.is_authenticated:
        return redirect('reviews:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('reviews:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

@login_required
def delete(request):
    request.user.delete()
    return redirect('reviews:index')


@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('reviews:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('reviews:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)

django/장고 실습 파일/0412장고실습/reviews/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_safe
from .models import Review, Comment
from .forms import ReviewForm, CommentForm


def index(request):
    reviews = Review.objects.order_by('-pk')
    context = {
        'reviews': reviews,
    }
    return render(request, 'reviews/index.html', context)


def detail(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    comments = review.comment_set.all()
    comment_form = CommentForm()
    context = {
        'review': review,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'reviews/detail.html', context)

@login_required
def create(request):
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('reviews:detail', review_pk=review.pk)

    else:
        form = ReviewForm()

    context = {
        'form': form,
    }

    return render(request, 'reviews/create.html', context)

@login_required
def delete(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.user == review.user:
        review.delete()

    return redirect('reviews:index')
@login_required
def update(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.user == review.user:

        if request.method == 'POST':
            form = ReviewForm(request.POST, instance=review)
            if form.is_valid():
                form.save()
                return redirect('reviews:detail', review.pk)
        else:
            form = ReviewForm(instance=review)
    else:
        return redirect('reviews:index')
    context = {
        'review': review,
        'form': form,
    }
    return render(request, 'reviews/update.html', context)


@login_required
def comment_create(request, review_pk):
    if request.method == "POST":
        review = Review.objects.get(pk=review_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.review = review
            comment.user = request.user
            comment.save()
        return redirect('reviews:detail', review.pk)

@login_required
def comment_delete(request, review_pk, comment_pk):
    if request.method == "POST":
        comment = Comment.objects.get(pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('reviews:detail', review_pk)

django/장고 실습 파일/0412장고실습/accounts/templates/accounts/change_password.html
{% extends "base.html" %}
{% block content %}
  <h1>비밀번호 변경</h1>
  <form action="{% url 'accounts:change_password' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
{% endblock content %}

django/장고 실습 파일/0412장고실습/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block content %}
  <div>
    <h1>로그인</h1>
    <form action="{% url 'accounts:login' %}" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="로그인">
    </form>
  </div>
{% endblock content %}

django/장고 실습 파일/0412장고실습/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
  <div>
    <h1>
      {{user}}님의 프로필 페이지
    </h1>

  </div>
{% endblock content %}

django/장고 실습 파일/0412장고실습/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
  <h1>회원가입</h1>
  <form action="{% url 'accounts:signup' %}" method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="회원 가입">
  </form>
{% endblock content %}

django/장고 실습 파일/0412장고실습/accounts/templates/accounts/update.html
{% extends "base.html" %}
{% block content %}
  <h1>회원정보 수정</h1>
  <form action="{% url 'accounts:update' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>

{% endblock content %}

django/장고 실습 파일/0412장고실습/reviews/templates/reviews/create.html
{% extends "base.html" %}
{% block content %}
  <h3>CREATE</h3>
  <form action="{% url 'reviews:create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-outline-secondary" type="submit" value="✍🏻글 작성"></input>
  </form>
{% endblock content %}

django/장고 실습 파일/0412장고실습/reviews/templates/reviews/detail.html
{% extends "base.html" %}
{% block content %}
  <h3>DETAIL</h3>
  <p>
    작성자 - 
    {{review.user}}
  </p>
  <p>
    후기 번호 -
    {{review.pk}}
  </p>
  <p>
    후기 제목 -
    {{review.title}}
  </p>
  <p>
    후기 내용 -
    {{review.content}}
  </p>
  <p>
    영화 이름 -
    {{review.movie}}
  </p>
  {% if request.user == review.user %}
    <form action="{% url 'reviews:delete' review.pk  %}" method="POST">
      {% csrf_token %}
      <input class="btn btn-outline-danger mb-2" type="submit" value="삭제">
    </form>
    <a class="btn btn-outline-success" href="{% url 'reviews:update' review.pk %}">UPDATE</a>
  {% endif %}
  <a class="btn btn-outline-secondary" href="{% url 'reviews:index' %}">back</a>
  <hr>
  <form action="{% url 'reviews:comment_create' review.pk %}" method="post">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <input class="btn btn-outline-secondary btn-sm" type="submit" value="✍🏻댓글 작성">
  </form>
  <hr>
  <h3>
    댓글 목록
  </h3>
  {% for comment in comments %}
    <div>
      <p>
        {{ comment.user }}
      </p>
      <p>댓글 번호 -
        {{ comment.pk }}</p>
      <p>
        댓글 내용 -
        {{comment.content}}
      </p>
      {% if request.user == comment.user %}
        <form action="{% url 'reviews:comment_delete' review.pk comment.pk %}" method="POST">
          {% csrf_token %}
          <input class="btn btn-outline-danger btn-sm" type="submit" value="댓글 삭제">
        </form>
      {% endif %}
    </div>
    <hr>
  {% endfor %}
{% endblock content %}

django/장고 실습 파일/0412장고실습/reviews/templates/reviews/index.html
{% extends "base.html" %}
{% block content %}
  <div>
   
    {% if request.user.is_authenticated %}
      <h3>
        {{ user }}
        님 안녕하세요!
      </h3>
      <div>
        <a class="btn btn-outline-secondary" href="{% url 'reviews:create' %}">✍🏻후기 작성</a>
      </div>
    {% else %}
      <h3>로그인을 해주세요!</h3>
      
    {% endif %}

  </div>
  {% for review in reviews %}
    <p>
      <p>
        작성자 - 
        {{review.user}}
      </p>
      <p>후기 번호 -
        {{ review.pk }}
      </p>
      <p>
        영화 이름 -
        {{review.movie}}
      </p>
    </p>
    <a class="btn btn-outline-secondary" href="{% url 'reviews:detail' review.pk %}">🔍detail</a>
    <hr>
  {% endfor %}
{% endblock content %}

django/장고 실습 파일/0412장고실습/reviews/templates/reviews/update.html
{% extends "base.html" %}
{% block content %}
  <h1>Edit</h1>
  <form action="{% url 'reviews:update' review.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-outline-success mb-2" type="submit" value="UPDATE">
  </form>
  <a class="btn btn-outline-secondary" href="{% url 'reviews:index' %}">back</a>
</body>
</html>
{% endblock content %}