django/장고 정리/09_ORM_with view_0330/09_django_orm_view_수업/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    # 데이터 삭제에 대한 URL 패턴
    path('<int:pk>/delete', views.delete, name='delete'),
    # 데이터 수정 페이지에 대한 URL 패턴
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
]

# 메인 주소 articles/
# 상세 페이지 주소 articles/1/

django/장고 정리/09_ORM_with view_0330/09_django_orm_view_수업/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

django/장고 정리/09_ORM_with view_0330/09_django_orm_view_수업/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class AccountBook(models.Model):
    note = models.CharField(max_length=80)
    description = models.TextField(null=True)
    category = models.CharField(max_length=20)
    amount = models.IntegerField(default=0)
    date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

django/장고 정리/09_ORM_with view_0330/09_django_orm_view_수업/articles/views.py
from django.shortcuts import render, redirect
from .models import Article



# Create your views here.
def index(request):
    # DB에 전체 게시글 조회를 요청하고 쿼리셋을 응답받아 저장
    articles = Article.objects.all()
    context = {
        'articles' : articles,
    }
    return render(request, 'articles/index.html', context)

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    # print(article)
    context = {
        'article' : article,
    }
    # context - 템플릿에 데이터와 함께 렌더링
    return render(request, 'articles/detail.html', context)


def new(request):
    return render(request, 'articles/new.html')

def create(request):
    # new에서 보낸 사용자 데이터를 받음
    title = request.POST.get('title')
    content = request.POST.get('content')
   
    # 받은 데이터를 DB에 저장
    # # 1 너무 길어서 탈락
    # article = Article()
    # article.title = title
    # article.content = content
    # article.save()

    # 2
    article = Article(title=title, content=content)
    # 저장 전에 유효성 검사와 같은 추가 작업을 위해 2번 방법을 택함
    article.save()

    # # 3 탈락 (사용자를 너무 믿음... 저장 전에 확인 해야 함)
    # Article.objects.create(title=title, content=content)

    # 결과 페이지 반환
    # return render (request, 'articles/create.html')

    # # 이동할 주소(URL) 사용자에게 응답
    # return redirect('articles:index')

    # 생성한 글의 단일 조회(detail) 주소(URL)로 이동 응답
    return redirect('articles:detail', article.pk )

def delete(request, pk): # request 사용 안함
    # 삭제할 데이터 조회 (기준=홈페이지에서전달받은 값)
    article = Article.objects.get(pk=pk)
    # 조회한 데이터 삭제
    article.delete()
    # 전체 조회 페이지 이동
    return redirect('articles:index')


def edit(request, pk):
    # 수정할 데이터 조회
    article = Article.objects.get(pk=pk)

    context = {
        'article' : article
    }
    return render(request, 'articles/edit.html', context)

def update(request, pk):
    article = Article.objects.get(pk=pk)

    article.title = request.POST.get('title')
    article.content = request.POST.get('content')

    article.save()
    return redirect('articles:detail', article.pk)

django/장고 정리/09_ORM_with view_0330/09_django_orm_view_수업/articles/templates/articles/create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h2>작성이 완료되었습니다.</h2>
</body>
</html>

django/장고 정리/09_ORM_with view_0330/09_django_orm_view_수업/articles/templates/articles/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Detail</h1>
  <p>글 번호: {{ article.pk }}</p>
  <p>제목: {{ article.title }}</p>
  <p>내용: {{ article.content }}</p>
  <p>작성일: {{ article.created_at }}</p>
  <p>수정일: {{ article.updated_at }}</p>
  <form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    {% comment %} <button type="submit"></button> {% endcomment %}
    <input type="submit" value="삭제">
  </form>
  {% comment %} a태그는 단순 이동 할 때 사용 {% endcomment %}
  <a href="{% url 'articles:edit' article.pk %}">[edit]</a>
  <a href="{% url 'articles:index' %}">[back]</a>
</body>
</html>

django/장고 정리/09_ORM_with view_0330/09_django_orm_view_수업/articles/templates/articles/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Edit</h1>
  {{ article }}
  <form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    <div>
      <label for="title">제목:</label>
      <input type="text" name="title" id="title" value="{{ article.title }}">
    </div>
    <div>
      <label for="content">내용: </label>
      <textarea name="content" id="content" cols="30" rows="10">{{ article.content }}</textarea>
    </div>
    <div>
      <input type="submit">
    </div>
  </form>
  <a href="{% url 'articles:index' %}">[back]</a>
</body>
</html>

django/장고 정리/09_ORM_with view_0330/09_django_orm_view_수업/articles/templates/articles/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Articles</h1>
  <a href="{% url 'articles:new' %}">[NEW]</a>
  {% comment %} <p>{{ articles }}</p> {% endcomment %}
  {% for article in articles %}
    <p>번호: {{ article.pk }}</p>
    <p>제목: 
      <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
    </p>
    <p>내용: {{ article.content }}</p>
    <hr>
  {% endfor %}
</body>
</html>

django/장고 정리/09_ORM_with view_0330/09_django_orm_view_수업/articles/templates/articles/new.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>New</h1>
  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    <div>
      <label for="title">제목:</label>
      <input type="text" name="title" id="title">
    </div>
    <div>
      <label for="content">내용: </label>
      <textarea name="content" id="content" cols="30" rows="10"></textarea>
    </div>
    <div>
      <input type="submit">
    </div>
  </form>
  <a href="{% url 'articles:index' %}">[back]</a>
</body>
</html>